# Generated by Django 4.2.15 on 2024-08-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_cake_cakeberry_cakedecor_cakelevel_cakeshape_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
