# Generated by Django 4.2.15 on 2024-08-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_rename_phonenumber_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pin',
            field=models.CharField(blank=True, max_length=4, verbose_name='pin'),
        ),
    ]
