# Generated by Django 4.2.15 on 2024-08-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_client_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, verbose_name='name'),
        ),
    ]
