# Generated by Django 4.2.15 on 2024-08-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_alter_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('text', models.TextField(verbose_name='Текст рекламы')),
                ('responses', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество откликов')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
            },
        ),
    ]
