# Generated by Django 4.2.15 on 2024-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cake", "0005_alter_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cake",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Время доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Дата доставки"
            ),
        ),
    ]
